import type { NextPage } from 'next'
import Head from 'next/head'
import NavBar from '../components/navbar'

const Home: NextPage = () => {
  return (
    <div >
      <Head>
        <title>Samuel Steiner</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      
      <div className="drawer">
        <input id="my-drawer-3" type="checkbox" className="drawer-toggle" /> 
        <div className="drawer-content flex flex-col">
          <div className="w-full md:w-64 md:h-screen navbar md:flex-col bg-base-300">
            <div className="flex-none md:hidden">
              <label htmlFor="my-drawer-3" className="btn btn-square btn-ghost">
                <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" className="inline-block w-6 h-6 stroke-current">
                  <path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M4 6h16M4 12h16M4 18h16" />
                  </svg>
              </label>
            </div> 
            
            <div className="flex-1 px-2 mx-2">Samuel Steiner</div>
            <div className="flex-none hidden md:block">
              <ul className="menu">
                <li><a>Home</a></li>
                <li><a>Navbar Item 2</a></li>
              </ul>
            </div>
          </div>
          
        </div> 
        <div className="drawer-side">
          <label htmlFor="my-drawer-3" className="drawer-overlay"></label> 
          <ul className="menu p-4 overflow-y-auto w-80 bg-base-100"> 
            <li><a>Sidebar Item 1</a></li>
            <li><a>Sidebar Item 2</a></li>
          </ul>
        </div>
      </div>
    </div>
  )
}

export default Home
